name: anime_ar
description: "An innovative AR-based anime character recognition app that uses camera feed to identify anime characters in real-time and overlays interactive information."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter dependencies
  # ar_flutter_plugin: ^0.7.3  # Temporarily disabled due to Android namespace issues
  camera: ^0.11.2
  # arcore_flutter_plugin: ^0.0.9  # Temporarily disabled - outdated, doesn't support null safety
  # permission_handler: ^10.4.5  # Temporarily disabled due to v1 embedding issues

  # AI and Image Processing
  tflite_flutter: ^0.11.0
  image: ^4.1.3

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  google_sign_in: ^6.2.0  # Use stable version 6.x

  # State Management and Navigation
  flutter_riverpod: ^2.4.5
  go_router: ^16.2.0

  # Local Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # Environment Variables and HTTP
  flutter_dotenv: ^6.0.0
  http: ^1.2.2
  dio: ^5.4.3+1

  # UI and Utilities
  cached_network_image: ^3.3.0
  share_plus: ^11.1.0
  flutter_animate: ^4.2.0
  vector_math: ^2.1.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/models/
    - assets/icons/
    - .env

  # Custom fonts for anime theme
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
          weight: 500
        - asset: assets/fonts/noto-sans-jp-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/NotoSansJP-Bold.otf
          weight: 700
    
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
    
    - family: RiiTN
      fonts:
        - asset: assets/fonts/RiiTN_R.otf
          weight: 400
